import { Metadata } from 'next';
import { Footer } from '../../components/layout/footer';
import { Sidebar } from '../../components/layout/sidebar';
import { SiteHeader } from '../../components/layout/site-header';
import { SidebarInset, SidebarProvider } from '../../components/ui/sidebar';
import { getClientDictionary } from '../../lib/get-dictionary';
import { Providers } from '../../service/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { locale, dict } = await getClientDictionary();
  return (
    <Providers locale={locale} dictionary={dict}>
      <SidebarProvider>
        <Sidebar dictionary={dict} />
        <SidebarInset>
          <SiteHeader />
          <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
            {children}
          </main>
        </SidebarInset>
      </SidebarProvider>
      <Footer />
    </Providers>
  );
}
