import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter, Lora } from 'next/font/google';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import { Toaster } from 'sonner';
import { defaultSettings } from '../service/context/settings-context';
import './globals.css';
import { getClientDictionary } from '../lib/get-dictionary';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const lora = Lora({ subsets: ['latin'], variable: '--font-lora' });

export default async function RootLayout({ children }: { children: ReactNode }) {
  const { locale } = await getClientDictionary();

  return (
    <html lang={locale} suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={`${inter.variable} ${lora.variable} font-sans scroll-smooth`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          themes={['light', 'dark', 'theme-museu', 'theme-birigui', 'system']}
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              style: { marginTop: '1rem' }, // Dá um respiro do topo da tela
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
